### ISSUE TITLE
Kepler fails when using `nameOverride`

### ISSUE THREAD

**Issue by bjornpijnacker** [sustainable-computing-io/kepler-helm-chart#64]
If the values field `nameOverride` is set, the Kepler deployment fails with the error:
```
E0805 08:24:49.232922       1 reflector.go:140] pkg/kubernetes/watcher.go:125: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:monitoring:kepler-rapl" cannot list resource "pods" in API group "" at the cluster scope: RBAC: clusterrole.rbac.authorization.k8s.io "kepler-clusterrole" not found
```

This occurs due to the following line, which doesn't respect the new name:
https://github.com/sustainable-computing-io/kepler-helm-chart/blob/main/chart/kepler/templates/rolebinding.yaml#L25

**Comment by yellowhat** [comment]
Ahhhh.

```yaml
kind: ClusterRole
  name: {{ include "kepler.name" . }}-clusterrole
# vs
kind: ClusterRole
name: {{ .Chart.Name }}-clusterrole
```

Let me create an MR
