### ISSUE TITLE
Helm chart 0.5.14: upgrade kepler-exporter from 0.7.12 to 0.8.0 - breaking change with mandatory config-dir ?

### ISSUE THREAD

**Issue by rcarre** [sustainable-computing-io/kepler-helm-chart#81]
https://github.com/sustainable-computing-io/kepler/issues/2041

**Comment by yellowhat** [comment]
Could you share your `values.yaml`, which helm command?

Please edit `5.0.14` to `0.5.14`.

**Comment by rcarre** [comment]
I got the reason why.

Here is an extract from `values.yaml`
```
securityContext:
  capabilities:
    drop: ["ALL"]
  privileged: true
  readOnlyRootFilesystem: true
```
As a consequence, setting up dir /`etc/kepler` is fordidden due to `readOnlyRootFilesystem: true`

Workaround by `kustomize patching` helm template rendering:
```
              - op: add
                path: "/spec/template/spec/volumes/4"
                value:
                  emptyDir:
                    sizeLimit: 1Mi
                  name: config-dir
              - op: add
                path: "/spec/template/spec/containers/0/volumeMounts/4"
                value:
                  name: config-dir
                  mountPath: /etc/kepler
```
